// config.js — the only file to touch when categories change.
window.SHEVET_CONFIG = {
  SHEET_ID: "1tRYgf0smzXqIrGJ1LdA-sF26Q3H8Zrw9zgbhrjlxZEM",
  TAB: "DB",
  TITLE: "שֵׁבֶט",
  KICKER: "ההמלצות של הקבוצה",
  CATEGORIES: [
    { name: "מדריכים", emoji: "🧭" },
    { name: "מנשאים", emoji: "🎒" },
    { name: "עגלות וסלקלים", emoji: "🛒" },
    { name: "הנקה ושאיבה", emoji: "🤱🏻" },
    { name: "האכלה", emoji: "🍼" },
    { name: "טיפוח ואמבטיה", emoji: "🛁" },
    { name: "שינה וניטור", emoji: "👶🏻" },
    { name: "ביגוד", emoji: "👕" },
    { name: "התפתחות ומשחק", emoji: "🧸" },
    { name: "ריהוט וחדר הילד", emoji: "🛏️" },
    { name: "ביגוד הריון והנקה לאם", emoji: "🤰🏻" },
    { name: "ערכות לידה ותיק לידה", emoji: "🧳" },
    { name: "התאוששות אחרי לידה", emoji: "🌸" },
    { name: "טיפוח ועור (לאם)", emoji: "🧴" },
    { name: "תוספי תזונה ומאכלים (לאם)", emoji: "🥗" },
    { name: "אנשי מקצוע ומטפלים", emoji: "🧑🏻‍⚕️" },
    { name: "בתי חולים וחוויות לידה", emoji: "🏥" },
    { name: "בדיקות, מעקב הריון וחיסונים", emoji: "🩺" },
    { name: "קורסי הכנה ללידה ושיטות", emoji: "🎓" },
    { name: "טיפול יומי בתינוק (גזים, עור, שינה)", emoji: "🌙" },
    { name: "מחקרים ודוחות", emoji: "📊" },
    { name: "פודקאסטים, ספרים ואפליקציות מומלצות", emoji: "🎧" },
    { name: "קבוצות וואטסאפ, קהילות וגמ\"חים", emoji: "💬" },
    { name: "עמודי רשתות חברתיות מומלצים", emoji: "📱" },
    { name: "מסמכים ואתרים שימושיים", emoji: "📄" },
    { name: "ספרים לקטנטנים", emoji: "📚" },
  ],
  FALLBACK_EMOJI: "📦",
  // Apps Script /exec URL for the add-item form; empty = button hidden.
  SUBMIT_URL: "https://script.google.com/macros/s/AKfycbxiJ0SU-pFt66oVLHbN0VFgvYp9PGDBqsOWCKa5x1JGMcfpBOBofwarqCaVDqClYH3njw/exec",
};
